export const STORE_PRODUCT = 'STORE_PRODUCT';
export const RETRIEVE_PRODUCT = 'RETRIEVE_PRODUCT';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';
export const EDIT_PRODUCT = 'EDIT_PRODUCT';
export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const EDIT_PRODUCT_QUANTITY_CART = 'EDIT_PRODUCT_QUANTITY_CART';
